meses=('','enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre')
print meses[1]
print meses[2]
print meses[3]
print meses[4]
print meses[5]
print meses[6]
print meses[7]
print meses[8]
print meses[9]
print meses[10]
print meses[11]
print meses[12]